-- CreateTable
CREATE TABLE `host` (
    `ID_HOST` INTEGER NOT NULL AUTO_INCREMENT,
    `CSID_HOST` VARCHAR(191) NULL,
    `NAME_HOST` VARCHAR(250) NULL,
    `ID_EMP_HOST` VARCHAR(250) NULL,
    `IP_GATEWAY_HOST` VARCHAR(250) NULL,
    `ZONE_HOST` VARCHAR(250) NULL,
    `PARTITION_HOST` VARCHAR(250) NULL,
    `STATUS_HOST` VARCHAR(250) NULL,
    `DT_EXEC` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DT_CREATED` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `host_ID_HOST_key`(`ID_HOST`),
    UNIQUE INDEX `host_CSID_HOST_key`(`CSID_HOST`),
    PRIMARY KEY (`ID_HOST`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `host_equipment` (
    `ID_EQUIPMENT` INTEGER NOT NULL AUTO_INCREMENT,
    `NAME_EQUIPMENT` VARCHAR(191) NULL,
    `PRODUCER_EQUIPMENT` VARCHAR(191) NULL,
    `MODEL_EQUIPMENT` VARCHAR(191) NULL,
    `HANDLE_HABILITY` VARCHAR(191) NULL,
    `IP_EQUIPMENT` VARCHAR(191) NULL,
    `STATUS_EQUIPMENT` VARCHAR(191) NULL,
    `DT_EXECUTE` DATETIME(3) NULL,
    `CSID_HOST` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `host_equipment_ID_EQUIPMENT_key`(`ID_EQUIPMENT`),
    PRIMARY KEY (`ID_EQUIPMENT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `host_equipment` ADD CONSTRAINT `host_equipment_CSID_HOST_fkey` FOREIGN KEY (`CSID_HOST`) REFERENCES `host`(`CSID_HOST`) ON DELETE RESTRICT ON UPDATE CASCADE;
