-- AlterTable
ALTER TABLE `host` MODIFY `CSID_HOST` VARCHAR(191) NULL,
    MODIFY `NAME_HOST` VARCHAR(191) NULL,
    MODIFY `ID_EMP_HOST` VARCHAR(191) NULL,
    MODIFY `IP_GATEWAY_HOST` VARCHAR(191) NULL,
    MODIFY `STATUS_HOST` VARCHAR(191) NULL,
    MODIFY `DT_CREATED` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `host_equipment` MODIFY `NAME_EQUIPMENT` VARCHAR(191) NULL,
    MODIFY `PRODUCER_EQUIPMENT` VARCHAR(191) NULL,
    MODIFY `MODEL_EQUIPMENT` VARCHAR(191) NULL,
    MODIFY `HANDLE_HABILITY` VARCHAR(191) NULL,
    MODIFY `IP_EQUIPMENT` VARCHAR(191) NULL,
    MODIFY `STATUS_EQUIPMENT` VARCHAR(191) NULL,
    MODIFY `DT_EXECUTE` DATETIME(3) NULL;
