-- CreateTable
CREATE TABLE `host` (
    `ID_HOST` INTEGER NOT NULL AUTO_INCREMENT,
    `CONTA` VARCHAR(191) NOT NULL,
    `NOME` VARCHAR(150) NULL,
    `ID_EMPRESA` VARCHAR(150) NULL,
    `IP_GATEWAY_HOST` VARCHAR(150) NULL,
    `DESCRICAO_HOST` VARCHAR(150) NULL,
    `ZONA_HOST` VARCHAR(150) NULL,
    `PARTICAO_HOST` VARCHAR(150) NULL,
    `QUANTIDADE_PING` VARCHAR(191) NULL DEFAULT '10',
    `PERCA_DE_PACOTE` VARCHAR(150) NULL,
    `STATUS_HOST` VARCHAR(191) NULL DEFAULT 'ON-LINE',
    `STATUS_INICIAL_EVENTO` VARCHAR(150) NOT NULL,
    `STATUS_ENVIO_EVENTO` VARCHAR(150) NOT NULL,
    `DT_EXECUCAO` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DT_CRIACAO` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `host_ID_HOST_key`(`ID_HOST`),
    PRIMARY KEY (`ID_HOST`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `event_host` (
    `ID_EVENT` INTEGER NOT NULL AUTO_INCREMENT,
    `HASH_ID_HASH` VARCHAR(191) NOT NULL,
    `STATUS_ENVIO_EVENTO_SIGMA` VARCHAR(191) NOT NULL DEFAULT 'PENDENTE',
    `CONTA_EVENTO` VARCHAR(191) NULL,
    `DESCRICAO_HOST` VARCHAR(150) NULL,
    `NOME_EVENTO` VARCHAR(150) NULL,
    `ID_EMPRESA__EVENTO` VARCHAR(150) NULL,
    `IP_GATEWAY_HOST_EVENTO` VARCHAR(150) NULL,
    `ZONA_HOST_EVENTO` VARCHAR(150) NULL,
    `PARTICAO_HOST_EVENTO` VARCHAR(150) NULL,
    `DT_CRIACAO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `event_host_ID_EVENT_key`(`ID_EVENT`),
    PRIMARY KEY (`ID_EVENT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
