-- AlterTable
ALTER TABLE `host` MODIFY `NAME_HOST` VARCHAR(250) NULL,
    MODIFY `ID_EMP_HOST` VARCHAR(250) NULL,
    MODIFY `IP_GATEWAY_HOST` VARCHAR(250) NULL,
    MODIFY `STATUS_HOST` VARCHAR(250) NULL,
    MODIFY `PARTITION_HOST` VARCHAR(250) NULL,
    MODIFY `ZONE_HOST` VARCHAR(250) NULL;
