-- CreateTable
CREATE TABLE `conta` (
    `ID_CONTA` INTEGER NOT NULL AUTO_INCREMENT,
    `CSID` INTEGER NOT NULL,
    `ID_EMPRESA` VARCHAR(10) NULL,
    `RAZAO` VARCHAR(150) NULL,
    `FANTASIA` VARCHAR(150) NULL,
    `ENDERECO` VARCHAR(150) NULL,
    `ESTADO` VARCHAR(50) NULL,
    `CIDADE` VARCHAR(50) NULL,
    `EMAIL_RESPOSAVEL` VARCHAR(50) NULL,
    `NUMERO_CELULAR` VARCHAR(50) NULL,
    `NUMERO_FIXO` VARCHAR(50) NULL,
    `DATA_CRIACAO` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DATA_ATUALIZACAO` DATETIME(3) NULL,

    UNIQUE INDEX `conta_ID_CONTA_key`(`ID_CONTA`),
    UNIQUE INDEX `conta_CSID_key`(`CSID`),
    PRIMARY KEY (`ID_CONTA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `equipamento` (
    `ID_EQUIPAMENTO` INTEGER NOT NULL AUTO_INCREMENT,
    `DESCRICAO` VARCHAR(191) NULL,
    `CSID` INTEGER NOT NULL,
    `ZONA` VARCHAR(50) NULL,
    `PARTICAO` VARCHAR(50) NULL,
    `ENDERECO_IP` VARCHAR(50) NULL,
    `QUANTIDADE_PING` INTEGER NULL DEFAULT 10,
    `DATA_CRIACAO` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `DATA_ATUALIZACAO` DATETIME(3) NULL,

    UNIQUE INDEX `equipamento_ID_EQUIPAMENTO_key`(`ID_EQUIPAMENTO`),
    PRIMARY KEY (`ID_EQUIPAMENTO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ping` (
    `ID_PING` INTEGER NOT NULL AUTO_INCREMENT,

    UNIQUE INDEX `ping_ID_PING_key`(`ID_PING`),
    PRIMARY KEY (`ID_PING`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `equipamento` ADD CONSTRAINT `equipamento_CSID_fkey` FOREIGN KEY (`CSID`) REFERENCES `conta`(`CSID`) ON DELETE RESTRICT ON UPDATE CASCADE;
